# Jekyll ì„¤ì • íŒŒì¼ì…ë‹ˆë‹¤.

# ì‚¬ì´íŠ¸ ê¸°ë³¸ ì •ë³´
title:              "ê°ìë„ìŠ¤"
description:        "ê°œë°œ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤."
author_name:        "ì†¡ë³‘ì¤€"
author_email:       song@potados.com
logo_url:           https://avatars1.githubusercontent.com/u/35878712?v=4

# ì†Œì…œ ë§í¬
social:
    github:         https://github.com/potados99
    instagram:      https://www.instagram.com/song.potados/

# ì‚¬ì´íŠ¸ ì„¤ì •
url:                https://blog.potados.com # main url
permalink:          /:categories/:title/ # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
new_badge_period:   7
heart_reaction:     "ğŸ’™" # í¬ìŠ¤íŠ¸ë³„ ì´ëª¨ì§€ë³„ë¡œ ì¹´ìš´íŠ¸ë¥¼ ì…‰ë‹ˆë‹¤. ë”°ë¼ì„œ ì´ ê°’ì„ ë°”ê¾¸ë©´ ì¹´ìš´íŠ¸ë„ ë°”ë€ë‹ˆë‹¤.

# ë¶„ì„
google_analytics:   UA-154995965-1

# ì‚¬ì´íŠ¸ ë¹Œë“œ
markdown:           kramdown
highlighter:        rouge
kramdown:
    input:          GFM
sass:
    style:          :compressed

# ê¸°íƒ€ íŒŒë¼ë¯¸í„°
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "Gemfile", "drafts"]
plugins:
  - jekyll-sitemap

# ì¡°ê±´ë§ˆë‹¤ ìë™ìœ¼ë¡œ ì ìš©í•  ê¸°ë³¸ ì†ì„±ë“¤
defaults:
  - scope:
      path:         ""
    values:
      layout:       "null"
  - scope:
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      type:         "posts"
    values:
      layout:       "post"
      comments:     true